Add randomisation of gold, rubber, and oil events.
ParadoxGameConverters/EU4toVic2 pull request #605
Opened 2020-10-29 13:28 UTC by kingofmen

This code creates a "Goods.txt" file containing events that change a province's RGO, replacing the existing events in vanilla Vicky that add historical gold rushes and oil and rubber production for the midgame. The created events are user-configurable; the configuration in this PR will roughly recreate the gold/rubber/oil setup from vanilla, except of the provinces picked are random. The configuration allows excluding some RGOs from the random generation; for example the player will usually be annoyed if their valuable sulphur province changes to produce worthless gold, so this can be excluded (and this configuration does so). The event generation is activated by the "Random RGOs" flag in the configuration, being meant for users who want an ahistorical resource setup. 

Please reject if you don't feel this is a good fit for the converter, I coded it for my own megacampaign and since it is easily separable from my other customisations I thought I'd see if you wanted it. :)

2020-10-29 13:41 UTC, kingofmen commented
Hmm... it builds on my desktop. Let me see if I can figure this out.

2020-10-29 13:42 UTC, kingofmen commented
Oh, I didn't fix the Makefiles, of course. Sorry, I'll fix it.

2020-10-30 02:02 UTC, Idhrendur requested changes
Also, add tests where reasonable. Zemurin can provide guidance on what's feasible in this converter.

2020-10-30 02:02 UTC, Idhrendur commented on EU4toV2/Source/V2World/Event/Event.h
> +                // Vicky event ID.
In general, no need for comments describing the variables. If its unclear, aim for a more descriptive name. If its still unclear, go ahead with a comment.

2020-12-29 11:32 UTC, IohannesIohannium commented
Could this be made optional? Perhaps some may wish for gold/rubber/oil to keep their historical setup

2020-12-29 19:34 UTC, Idhrendur commented
I believe it's tied to the already optional randomize rgo functionality. This just extends it to rgos that are created by event.

2021-01-11 12:27 UTC, kingofmen commented
> Could this be made optional? Perhaps some may wish for gold/rubber/oil to keep their historical setup

As Idhrendur says, it's already behind the option to randomise RGOs. Did you intend to make them separate options, so that someone could have random RGOs but historical gold/rubber/oil?

2021-01-11 14:24 UTC, IohannesIohannium commented
No need for two separate options. I had just forgotten that we had one
already.

2021-04-27 20:12 UTC, Zemurin commented
I'll be closing this for now, but will keep in mind if a need for this ever arises again.

2021-04-27 20:12 UTC, closed without merging