New Religion Update
ParadoxGameConverters/EU4toVic2 pull request #635
Opened 2020-12-06 05:27 UTC by Elfangor567

PLEASE HAVE SOMEONE FAMILIAR WITH MODDING VIC2 REVIEW THIS. THIS IS MY FIRST TIME MODDING FOR THIS GAME, AND I DO NOT WISH TO ACCIDENTALLY BREAK THE COVNERTER.

- Updated for new Reformed Siberians. (From CK3)
- Added pagan_religion_reformed (CK2)
- Moved all Gnostic faiths to link to Gnostic
- Moved all Yazidi faiths to link to Yazidi

2020-12-06 05:48 UTC, Idhrendur commented
It's been a long time since I touched any of that (EU3 to Vic2 days, most likely), but it all looks correct.

2020-12-06 05:48 UTC, Idhrendur approved these changes

2020-12-06 09:15 UTC, IohannesIohannium commented
You need to add these in blankMod/output/events/
[Noculture.txt](https://github.com/ParadoxGameConverters/EU4toVic2/files/5648526/Noculture.txt)
[postColonial.txt](https://github.com/ParadoxGameConverters/EU4toVic2/files/5648527/postColonial.txt)

2020-12-06 09:16 UTC, IohannesIohannium requested changes
⸻

2020-12-07 20:39 UTC, Zemurin approved these changes

2020-12-07 21:23 UTC, merged