Compatibility with the Random Content Mod
ParadoxGameConverters/EU4toVic2 pull request #734
Opened 2021-06-07 21:42 UTC by CarbonY26

Issue #732

2021-06-08 04:32 UTC, CarbonY26 commented
Why did it separate the PR into 2?

2021-06-08 15:22 UTC, CarbonY26 commented
Now for the flags and other stuff

2021-06-08 17:31 UTC, IohannesIohannium requested changes
Missing files needed: LNC_monarchy.tga, LNC_republic.tga, LNC_communism.tga and LNC_fascism.tga
All of these, along with LNC.tga, should be then copied in Vic2toHoi4

2021-06-08 17:31 UTC, IohannesIohannium commented on EU4toV2/Data_Files/blankMod/output/common/countries.txt
> +LNC		="countries/Lancaster.txt"##
You can remove both LNC and LOI lines as they're not strictly needed. If the output has Lancaster, it'll be correctly set already; if not, there is no need for it, as we summon not these tags in decisions or events.
If you want to keep them, however, you must add the relevant localisations on 0_Names.csv

2021-06-16 03:37 UTC, CarbonY26 commented
Going to restructure this PR.

2021-06-16 03:37 UTC, closed without merging